// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUhlP7bzMHt849dE1EFLiSTuEPPfgEnHk',
    appId: '1:308257825005:web:5cd544d17d55d094f06ce4',
    messagingSenderId: '308257825005',
    projectId: 'robot-project-94443',
    authDomain: 'robot-project-94443.firebaseapp.com',
    storageBucket: 'robot-project-94443.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDXgCsfiVSq6hTJwNx2lw4bu3XvZ46mj4',
    appId: '1:308257825005:android:d1fa8bf9e3e31549f06ce4',
    messagingSenderId: '308257825005',
    projectId: 'robot-project-94443',
    storageBucket: 'robot-project-94443.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbmWJ_SesXMuP4YXQAfQBSN86JbegyjtM',
    appId: '1:308257825005:ios:6aa06c1e75d9e726f06ce4',
    messagingSenderId: '308257825005',
    projectId: 'robot-project-94443',
    storageBucket: 'robot-project-94443.firebasestorage.app',
    iosBundleId: 'com.example.visionFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbmWJ_SesXMuP4YXQAfQBSN86JbegyjtM',
    appId: '1:308257825005:ios:6aa06c1e75d9e726f06ce4',
    messagingSenderId: '308257825005',
    projectId: 'robot-project-94443',
    storageBucket: 'robot-project-94443.firebasestorage.app',
    iosBundleId: 'com.example.visionFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUhlP7bzMHt849dE1EFLiSTuEPPfgEnHk',
    appId: '1:308257825005:web:9b33923e1cdf881af06ce4',
    messagingSenderId: '308257825005',
    projectId: 'robot-project-94443',
    authDomain: 'robot-project-94443.firebaseapp.com',
    storageBucket: 'robot-project-94443.firebasestorage.app',
  );
}
